"""Structured Pydantic Output Schemas for all 5 specialized DataPilot Agents."""

from typing import Optional, List, Dict, Any, Literal
from pydantic import BaseModel, Field


class SupervisorOutput(BaseModel):
    """Structured output for the Supervisor Agent routing decision."""
    intent_summary: str = Field(description="Summary of the user's intent")
    next_agent: Literal["profiler", "analyst", "visualization", "insight", "end"] = Field(
        description="Target specialized agent node to route work to"
    )
    plan_steps: List[str] = Field(
        default_factory=list,
        description="Multi-step analytical plan steps to fulfill the user request"
    )
    reasoning: str = Field(description="Explanation for the routing decision")


class ProfilerOutput(BaseModel):
    """Structured output for the Data Profiler Agent."""
    dataset_summary: str = Field(description="High-level overview of dataset shape and column classifications")
    quality_score: float = Field(description="Composite data quality score from 0.0 to 100.0")
    critical_warnings: List[str] = Field(
        default_factory=list,
        description="Identified data quality issues, missingness warnings, or duplicate row flags"
    )
    key_column_observations: List[str] = Field(
        default_factory=list,
        description="Key statistical or distributional observations across columns"
    )


class AnalysisPlanStep(BaseModel):
    """A single analytical step in an analysis plan."""
    tool_name: str = Field(
        description="Name of tool to execute: filter_data, group_data, aggregate_data, calculate_statistics, calculate_correlation, analyze_trend, detect_anomalies, custom_sandbox"
    )
    params: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters for the tool execution"
    )
    purpose: str = Field(description="Objective of this step")


class AnalysisPlan(BaseModel):
    """Structured analysis plan generated by LLM planner."""
    analysis_goal: str = Field(description="Goal of the analysis plan")
    steps: List[AnalysisPlanStep] = Field(
        default_factory=list,
        description="Sequence of analytical steps"
    )
    recommended_visualization: bool = Field(
        default=False,
        description="Whether LLM recommends visualization"
    )


class AnalystOutput(BaseModel):
    """Structured output for the Data Analyst Agent."""
    analysis_goal: str = Field(description="Objective of the analysis execution step")
    tool_calls_planned: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of tools and parameters planned by LLM planner"
    )
    tool_calls_executed: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of tools and parameters actually executed by application"
    )
    execution_status: Literal["success", "partial_success", "failed"] = Field(
        default="success",
        description="Execution outcome status: success, partial_success, failed"
    )
    quantitative_results: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured quantitative metrics and rows returned by executed tools"
    )
    findings_summary: str = Field(default="", description="Quantitative summary of analysis results based on actual tool outputs")
    requires_visualization: bool = Field(
        default=False,
        description="Validated determination of whether visualization is recommended"
    )
    errors: List[str] = Field(
        default_factory=list,
        description="Warnings or error messages encountered during plan validation or tool execution"
    )


class VisualizationOutput(BaseModel):
    """Structured output for the Visualization Agent."""
    is_useful: bool = Field(description="Whether visualization is helpful for this user query")
    chart_type: Optional[Literal["bar", "line", "scatter", "histogram", "boxplot", "pie"]] = Field(
        default=None,
        description="Selected chart type"
    )
    x_column: Optional[str] = Field(default=None, description="Primary X-axis column name")
    y_column: Optional[str] = Field(default=None, description="Secondary Y-axis column name if applicable")
    title: Optional[str] = Field(default=None, description="Descriptive chart title")
    chart_file_path: Optional[str] = Field(default=None, description="Saved PNG chart file path")
    base64_image: Optional[str] = Field(default=None, description="Base64 data URI string of saved PNG chart")
    reasoning: str = Field(description="Rationale for chart selection and formatting")


class InsightOutput(BaseModel):
    """Structured output for the Insight Agent."""
    executive_summary: str = Field(description="High-level executive answer addressing user question")
    key_insights: List[str] = Field(
        default_factory=list,
        description="Bulleted business insights derived from numerical results and visualizations"
    )
    actionable_recommendations: List[str] = Field(
        default_factory=list,
        description="Actionable strategic recommendations for stakeholders"
    )
    confidence_score: float = Field(
        default=1.0,
        description="Confidence score (0.0 to 1.0) based on data completeness and analysis precision"
    )
    hypotheses: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Structured statistical hypotheses evidence and p-value metrics"
    )
    structured_insights: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Structured machine-readable business insights with evidence metadata"
    )
    suggested_followups: List[str] = Field(
        default_factory=list,
        description="Context-aware suggested follow-up queries derived from actual empirical findings"
    )



class AgentQueryRequest(BaseModel):
    """Request schema for POST /api/v1/query agent execution endpoint."""
    query: str = Field(description="User natural language analytical question or command")
    dataset_id: Optional[str] = Field(default=None, description="Optional registered dataset ID")
    session_id: Optional[str] = Field(default=None, description="Optional conversation session ID")


class AgentQueryResponse(BaseModel):
    """Response schema for POST /api/v1/query agent execution endpoint."""
    session_id: str = Field(description="Active session ID for multi-turn conversation tracking")
    query: str = Field(description="Original user query")
    rewritten_query: Optional[str] = Field(default=None, description="Contextually rewritten query if applicable")
    next_agent: str = Field(description="Final agent target reached in workflow")
    supervisor: Optional[SupervisorOutput] = Field(default=None, description="Supervisor Agent output")
    profiler: Optional[ProfilerOutput] = Field(default=None, description="Data Profiler Agent output")
    analyst: Optional[AnalystOutput] = Field(default=None, description="Data Analyst Agent output")
    visualization: Optional[VisualizationOutput] = Field(default=None, description="Data Visualization Agent output")
    insight: Optional[InsightOutput] = Field(default=None, description="Executive Insight Agent output")
    history: List[str] = Field(default_factory=list, description="Execution step history trace")
    errors: List[str] = Field(default_factory=list, description="Errors or warnings encountered during execution")
